[package]
name = "pak_parser"
version = "0.1.0"
edition = "2021"

[lib]
name = "pak_parser"
crate-type = ["cdylib"]

[dependencies]

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
rpath = false
debug = false
